name: user_repository
description: "the repo that handle users"

publish_to: 'none' 


version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  firebase_storage: ^11.7.6
  google_sign_in: ^6.2.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

