// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC775-HvZZj3BMZ8WqIM7ogaiLHOGQOBaw',
    appId: '1:350290070011:web:2e1b8bb7d1abee564fe35e',
    messagingSenderId: '350290070011',
    projectId: 'rashid-3b5e0',
    authDomain: 'rashid-3b5e0.firebaseapp.com',
    storageBucket: 'rashid-3b5e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3TDT3m-AZfB3WBTaRycKnvDekGFGR28o',
    appId: '1:350290070011:android:82d57545ba76eee74fe35e',
    messagingSenderId: '350290070011',
    projectId: 'rashid-3b5e0',
    storageBucket: 'rashid-3b5e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcq6zMW9CEC__HmxPH3joCjo5Nk2X-2dc',
    appId: '1:350290070011:ios:348631a6920712c14fe35e',
    messagingSenderId: '350290070011',
    projectId: 'rashid-3b5e0',
    storageBucket: 'rashid-3b5e0.appspot.com',
    iosBundleId: 'com.example.rashid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcq6zMW9CEC__HmxPH3joCjo5Nk2X-2dc',
    appId: '1:350290070011:ios:348631a6920712c14fe35e',
    messagingSenderId: '350290070011',
    projectId: 'rashid-3b5e0',
    storageBucket: 'rashid-3b5e0.appspot.com',
    iosBundleId: 'com.example.rashid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC775-HvZZj3BMZ8WqIM7ogaiLHOGQOBaw',
    appId: '1:350290070011:web:27232006320d66c64fe35e',
    messagingSenderId: '350290070011',
    projectId: 'rashid-3b5e0',
    authDomain: 'rashid-3b5e0.firebaseapp.com',
    storageBucket: 'rashid-3b5e0.appspot.com',
  );
}
