name: ai_courses_repository
description: "the repo that handle ai courses"

publish_to: 'none' 


version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2
  flutter_gemini: ^2.0.4
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.6
  path_provider: ^2.1.3
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

